baseURL = "https://tolkunov.dev"
title = "Ivan Tolkunov"
languageCode = "en-us"
theme = "archie"
enableRobotsTXT = true

[pagination]
pagerSize = 10

[[menu.main]]
identifier = "home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "Resume"
title = "Resume"
url = "/ivan_tolkunov_software_engineer.pdf"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 4

[params]
author = "Ivan Tolkunov"
subtitle = "Software engineer based in Toronto, focused on building practical AI tools."
mode = "auto"
useCDN = false
mainSections = ["posts"]

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:tolkunov.ivan.s@gmail.com"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ivan-tolkunov"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ivantolkunov/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/zxcubika"

[markup.goldmark.renderer]
unsafe = true
